### PR TITLE
[DSCP-193] Remove avlp

### PR DESCRIPTION
**Pull request by Heimdell**
We need this by demand of @volhovm .

The implementation of AVLp driver was moved to Disciplina and reworked a bit.

### CODE REVIEW

**Comment by volhovm** [comment]
@georgeee what's your argumentation on not merging this PR? My point is that:
* SD version of AVLp adapter is complex, unreadable and undocumented 
* It is not used, it's hard to maintain
* AVLp integration is rewritten properly in the only place we really need it (dscp)

If your point is to say "better abstract then move out and specialise", my response is:
* Sometimes abstraction is not the best solution (who else needs avlp excepts dscp)
* Even if we decide to abstract, it's worth first moving it to the DSCP so we can deliver bugfixes quickly.

**Comment by pva701** [comment]
2018-05-22 13_41_37-window

**Comment by georgeee** [comment]
@volhovm @Heimdell 

I'm tired of you DSCP folks being not collaborative. Instead of maintaining library you extract particular modules and edit it within your project. Ok, you want to do it -- I don't complain. But I won't remove these modules from snowdrop only because you don't need them any more. It's not only DSCP team who uses the AVL+ module, we also have it plugged into snowdrop's demo and it's being in regular use for testing and experimentation.

**Comment by volhovm** [comment]
>I'm tired of you DSCP folks being not collaborative

It's not about the lack of collaboration but rather about the effectiveness of what we do.

You also completely disregarded all other points that I made.

**Pull request closed without merging**
